// Code generated by mockery v2.43.0. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/kriuchkov/postero/internal/core/models"
	mock "github.com/stretchr/testify/mock"
)

// MockMessageRepository is an autogenerated mock type for the MessageRepository type
type MockMessageRepository struct {
	mock.Mock
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockMessageRepository) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)
	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockMessageRepository) GetByID(ctx context.Context, id string) (*models.Message, error) {
	ret := _m.Called(ctx, id)
	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *models.Message
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.Message); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Message)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: ctx, limit, offset
func (_m *MockMessageRepository) List(ctx context.Context, limit int, offset int) ([]*models.Message, error) {
	ret := _m.Called(ctx, limit, offset)
	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*models.Message
	if rf, ok := ret.Get(0).(func(context.Context, int, int) []*models.Message); ok {
		r0 = rf(ctx, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Message)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = rf(ctx, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MarkAsRead provides a mock function with given fields: ctx, id
func (_m *MockMessageRepository) MarkAsRead(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)
	if len(ret) == 0 {
		panic("no return value specified for MarkAsRead")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MarkAsSpam provides a mock function with given fields: ctx, id
func (_m *MockMessageRepository) MarkAsSpam(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)
	if len(ret) == 0 {
		panic("no return value specified for MarkAsSpam")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Save provides a mock function with given fields: ctx, message
func (_m *MockMessageRepository) Save(ctx context.Context, message *models.Message) error {
	ret := _m.Called(ctx, message)
	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Message) error); ok {
		r0 = rf(ctx, message)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Search provides a mock function with given fields: ctx, criteria
func (_m *MockMessageRepository) Search(ctx context.Context, criteria models.SearchCriteria) ([]*models.Message, error) {
	ret := _m.Called(ctx, criteria)
	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 []*models.Message
	if rf, ok := ret.Get(0).(func(context.Context, models.SearchCriteria) []*models.Message); ok {
		r0 = rf(ctx, criteria)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Message)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, models.SearchCriteria) error); ok {
		r1 = rf(ctx, criteria)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockMessageRepository creates a new instance of MockMessageRepository. It also registers a testing interface on the mock and a cleanup function to assert the mock's expectations.
// The first argument is typically a *testing.T value.
func NewMockMessageRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMessageRepository {
	mock := &MockMessageRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
